config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'homes#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'

  resources :homes

  resources :newfeeds

  resources :banners

  resources :users

  resources :infos

  resources :article_stores do
    resources :articles
  end

  resources :book_stores do
    resources :books
  end

  resources :lecture_stores do
    resources :lectures
  end

  resources :rule_stores do
    resources :rules
  end

  resources :photo_stores do
    resources :albums do
      resources :photos
    end
  end

  resources :others do
    resources :other_items do
      resources :other_item_details
    end
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :photo_store
  has_many :photos, :dependent => :destroy
  has_many :newfeeds, :dependent => :destroy
end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :article_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/banner.rb
class Banner < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :book_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/book_store.rb
class BookStore < ActiveRecord::Base
  has_many :books, :dependent => :destroy
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/info.rb
class Info < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  has_many :newfeeds, :dependent => :destroy
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :lecture_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/newfeed.rb
class Newfeed < ActiveRecord::Base
end

app/models/other.rb
class Other < ActiveRecord::Base
  has_many :other_items, :dependent => :destroy
end

app/models/other_item.rb
class OtherItem < ActiveRecord::Base
  has_many :other_item_details, :dependent => :destroy
  belongs_to :other
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :url, PictureUploader
  belongs_to :album

  def next album_id
    Photo.where(album_id: album_id).where("photos.id > ? ", self.id).order("photos.id ASC").limit(1)
  end

  def previous album_id
    Photo.where(album_id: album_id).where("photos.id < ?", self.id).order("photos.id DESC").limit(1)
end

end

app/models/photo_store.rb
class PhotoStore < ActiveRecord::Base
  has_many :albums, :dependent => :destroy
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  mount_uploader :image_upload, PictureUploader
  belongs_to :rule_store
  has_many :newfeeds, :dependent => :destroy
end

app/models/rule_store.rb
class RuleStore < ActiveRecord::Base
  has_many :rules, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save   :downcase_email
  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
            format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive:false}
  has_secure_password
  validates :password, length: {minimum: 6}, allow_blank: true
  
  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def index
    @infos = Info.order('created_at DESC').paginate(page: params[:page], per_page: 10)
  end

  def new
    @info = Info.new
  end

  def create
    @info = Info.new info_params
    if @info.save

     @newfeed = Newfeed.new
     @newfeed.info_id = @info.id
     @newfeed.save

      redirect_to infos_path
    else
    	flash[:danger] = "Create fails, please retry."
      render 'new'
    end
  end

  def show
    @infos = Info.order('created_at DESC')
    @info = Info.find params[:id]
  end

  def edit
    @info = Info.find params[:id]
  end

  def update
    @info = Info.find params[:id]
    if @info.update_attributes info_params
      redirect_to infos_path
    else
      render 'edit'
    end
  end

  def destroy
    @info = Info.find params[:id]
    @info.destroy
    redirect_to infos_path
  end

  private
  def info_params
    params.require(:info).permit(:name, :content, :during, :place, :description, :image_link, :image_upload)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/infos/_info.html.erb
<% if !info.image_link.empty? %>
<% @image = info.image_link %>
<% elsif(info.image_upload!=nil && !info.image_upload.empty?) %>
<% @image = info.image_upload.url %>
<% end %>
<div class="thumbnail thumbnail_w_h_news_container " data-example-id="simple-thumbnails">
        <div class="thumbnail thumbnail_w_h_news">
          <%= link_to (image_tag @image), info_path(info) %>
        </div>
        <div class="caption">
            <%= link_to info.name, info_path(info)%>
        </div>
        <div class="truncate">
        <p>
            <%= info.content.truncate_words(150).html_safe%>
            <%= link_to "Chi tiết", info_path(info), class: "news_detail"%>
        </p>
        </div>
        <div class="small_info_time">
         <%= info.created_at.to_date %>
        </div>

  </div>

app/views/infos/edit.html.erb
<div class="bs-example" data-example-id="basic-forms">
  <%= form_for @info, method: :patch do |f| %>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, class: "form-control",
                                  placeholder: "Name" %>
    </div>
    <div class="form-group">
      <label>During</label>
      <%= f.text_field :during, class: "form-control",
                                  placeholder: "During" %>
    </div>
    <div class="form-group">
      <label>Place</label>
      <%= f.text_field :place, class: "form-control",
                                  placeholder: "Place" %>
    </div>
    <div class="form-group">
      <label>Description</label>
      <%= f.text_field :description, class: "form-control",
                                  placeholder: "Description" %>
    </div>
    <div class="form-group">
      <label>Image-link</label>
      <%= f.text_field :image_link, class: "form-control",
                                  placeholder: "Image_link" %>
    </div>
    <div class="form-group">
      <label>Image-file</label>
      <%= f.file_field :image_upload, type: :file %>
    </div>
    <div class="form-group">
      <label>Content</label>
      <%= f.text_area :content, class: "form-control",
                                  placeholder: "Content" %>
    </div>
    <button type="submit" class="btn btn-default">Create
    </button>
  <% end %>
</div>

app/views/infos/index.html.erb
<ol class="breadcrumb">
  <li class="active"><%= "Tin tức" %></li>
</ol>
<% if logged_in? %>
<div class="bs-example">
    <ul class="nav nav-pills" role="tablist">
      <li role="presentation" class="dropdown">
        <a id="drop4" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
          Action
          <span class="caret"></span>
        </a>
        <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
          <li role="presentation">
            <%= link_to "Add news", new_info_path%>
          </li>
          <li role="presentation" class="divider"></li>
        </ul>
      </li>
    </ul> <!-- /pills -->
  </div>
<% end %>

<div class="breadcrumb_retative">
<ol class="breadcrumb breadcrumb_retative bg_breadcrumb">
  <li class="referent">Bài liên quan</li>
  </ol>
<div class=" bg_white_color breadcrumb_retative">
<% @infos.sample(10).each do |info| %>
  <div class="thumbnail caption news_title_thumnail">
  <span class="glyphicon glyphicon-pushpin" aria-hidden="true">
  </span>
     <%= link_to info.name, info_path(info) %>
    <div class="small_info_time">
     <%= info.created_at.to_date %>
   </div>
   </div>
<hr>
<% end %>
</div>
</div>

<%= render  @infos, cache: true %>
  <%#= render text: "123" %>

<a href="#top" id ="backToTopBtn">
  <img src="/assets/top.png" width="50px"></img>
</a>

<div class="thumbnail thumbnail_w_h_news_container center" data-example-id="simple-thumbnails">
    <%= will_paginate @infos%>
</div>

app/views/infos/new.html.erb
<div class="bs-example" data-example-id="basic-forms">
  <%= form_for(@info, html: {multipart: true}) do |f| %>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, class: "form-control",
                                  placeholder: "Name" %>
    </div>
    <div class="form-group">
      <label>During</label>
      <%= f.text_field :during, class: "form-control",
                                  placeholder: "During" %>
    </div>
    <div class="form-group">
      <label>Place</label>
      <%= f.text_field :place, class: "form-control",
                                  placeholder: "Place" %>
    </div>
    <div class="form-group">
      <label>Description</label>
      <%= f.text_field :description, class: "form-control",
                                  placeholder: "Description" %>
    </div>
      <div class="form-group">
      <label>Image-link</label>
      <%= f.text_field :image_link, class: "form-control",
                                  placeholder: "Image_link" %>
    </div>
    <div class="form-group">
      <label>Image-file</label>
      <%= f.file_field :image_upload, type: :file%>
    </div>

    <div class="form-group">
      <label>Content</label>
      <%= f.text_area :content, class: "form-control",
                                  placeholder: "Content" %>
    </div>

    <button type="submit" class="btn btn-default">Create
    </button>
  <% end %>
</div>

app/views/infos/show.html.erb
 <ol class="breadcrumb">
  <li><%= link_to "Tin tức", infos_path %></li>
  <li class="active"><%= @info.name %></li>
</ol>

<% if logged_in? %>
<div class="bs-example">
    <ul class="nav nav-pills" role="tablist">
      <li role="presentation" class="dropdown">
        <a id="drop4" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
          Action
          <span class="caret"></span>
        </a>
        <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
          <li role="presentation">
            <%= link_to "Edit.", edit_info_path(@info) %>
          </li>
          <li role="presentation">
            <%= link_to "Delete.", info_path(@info),
                    method: :delete,
                    data: { confirm: 'Make sure you want to do this?' }%>
          </li>
        </ul>
      </li>
    </ul> <!-- /pills -->
  </div>
<% end %>
<div class="jumbotron jumbotron_clip">
<i><div class="small_info_time">
<%= @info.created_at.to_date.to_date%>
</div></i>
  <div class="title_show">
      <%= @info.name %>
  </div>
  <%= @info.content.html_safe%>
  <br><br>
    Thời gian : <%= @info.during %>
  <br><br>
    Địa điểm : <%= @info.place %>
    <br><br><br><br>
          <a href="https://twitter.com/share" class="twitter-share-button">Tweet
          </a>
          <div class="fb-like" data-href=<%= request.original_url %> data-layout="standard" data-action="like" data-show-faces="true" data-share="true">
          </div>
</div>

<div class="breadcrumb_retative">
<ol class="breadcrumb breadcrumb_retative bg_breadcrumb">
  <li class="referent">Bài liên quan</li>
  </ol>
<div class=" bg_white_color breadcrumb_retative">
<% @infos.sample(10).each do |info| %>
  <span class="glyphicon glyphicon-pushpin" aria-hidden="true">
  </span>
   <%= link_to info.name, info_path(info) %>
                       <h6>
       <em>
       <small ><%= info.created_at %></small>
       </em>
     </h6>
<hr>
<% end %>
</div>
</div>

<div class="jumbotron jumbotron_clip">
  <div class="fb-comments" 
    data-href=<%= request.original_url %> data-width="100%" data-numposts="5" data-colorscheme="light">
  </div>
</div>